server:
  port: ${SERVER_PORT:8445}
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: mypass
    key-store-type: PKCS12

REDIRECT_URI: https://localhost:8445/index.html
APP_ID: ${APP_ID}
APP_SECRET: ${APP_SECRET}